[package]
name = "mevi-payload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.1.26"
passfd = "0.1.6"
userfaultfd = "0.5.0"
